export const checkValidKey = (key) => {
  switch (key) {
    case 'KeyQ':
      return true;
    case 'KeyW':
      return true;
    case 'KeyE':
      return true;
    case 'KeyR':
      return true;
    case 'KeyT':
      return true;
    case 'KeyY':
      return true;
    case 'KeyU':
      return true;
    case 'KeyI':
      return true;
    case 'KeyO':
      return true;
    case 'KeyP':
      return true;
    case 'KeyA':
      return true;
    case 'KeyS':
      return true;
    case 'KeyD':
      return true;
    case 'KeyF':
      return true;
    case 'KeyG':
      return true;
    case 'KeyH':
      return true;
    case 'KeyJ':
      return true;
    case 'KeyK':
      return true;
    case 'KeyL':
      return true;
    case 'KeyZ':
      return true;
    case 'KeyX':
      return true;
    case 'KeyC':
      return true;
    case 'KeyV':
      return true;
    case 'KeyB':
      return true;
    case 'KeyN':
      return true;
    case 'KeyM':
      return true;
    case 'Enter':
      return true;
    case 'Backspace':
      return true;
    default:
      return false;
  }
};
